- name: rabbitmq configuration
  hosts: rabbitmq
  become: true
  tasks:
  - name: copy file rabbitmq-package repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
  
  - name: Install rabbitmq server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: start service rabbitmq, if not started
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: true

# use module
  - name: creat user for application in rabbitmq
    ansible.builtin.command: "rabbitmqctl add_user roboshop roboshop123"

  - name: set_permissions for user  in rabbitmq
    ansible.builtin.command: 'rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"'


  