- name: frontend component configuration
  hosts: frontend
  become: true 
  tasks:
  - name: disable current nginx module 
    ansible.builtin.command: "dnf module disable nginx -y"

  - name: enable nginx:1.24 module 
    ansible.builtin.command: "dnf module enable nginx:1.24 -y"

  - name: install nginx 
    ansible.builtin.package:
      name: nginx 
      state: present

  - name: start service nginx, if not started
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: remove default nginx directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /tmp/frontend.zip

  - name: create default nginx directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

    
  - name: extract application code /tmp/frontend.zip
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: true

  - name: remove default nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy config file to /etc/nginx/
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart service nginx
    ansible.builtin.service:
      name: nginx
      state: restarted