  - name: application set-up
    include_role:
      name: common
      tasks_from: app-setup.yaml

  - name: install nodejs 
    include_role:
      name: common
      tasks_from: nodejs-setup.yaml


  - name: copy service file to /etc/systemd/system/
    ansible.builtin.template:
      src: templates/catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
    

  - name: copy file mongo-package repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.royalreddy.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.royalreddy.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: start catalogue service
    include_role:
      name: common
      tasks_from: systemd-service.yaml