- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: copy file mongo-package repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.command: "dnf install mongodb-org -y"

  - name: start service mongod, if not started
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: true
      
  - name: update listen address from 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart service mongod
    ansible.builtin.service:
      name: mongod
      state: restarted

  - name: check mongod version
    ansible.builtin.command: "mongod --version"
    register: mongod_version 

  - name: print mongod_version
    ansible.builtin.debug: 
      msg: "{{ mongod_version.stdout }}"

    