- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: copy file mongo-package repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb
    ansible.builtin.command: "dnf install mongodb-org -y"

  - name: start service mongod, if not started
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: true
      
  - name: update listen address from 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart service mongod
    ansible.builtin.service:
      name: mongod
      state: restarted

- name: Extract only MongoDB version (e.g., 7.0.20)
  ansible.builtin.set_fact:
    mongo_version: "{{ mongod_version.stdout | regex_search('(?<=db version v)([0-9\\.]+)', '\\1') }}"
  when: mongod_version is defined and mongod_version.rc == 0

- name: Print extracted MongoDB version
  ansible.builtin.debug:
    msg: "MongoDB Version: {{ mongo_version }}"
      