- name: redis configuratiion
  hosts: redis
  become: true 
  tasks:
  - name: disable current redis module 
    ansible.builtin.command: "dnf module disable redis -y"

  - name: enable redis:7 module 
    ansible.builtin.command: "dnf module enable redis:7 -y"

  - name: install redis  
    ansible.builtin.package:
      name: redis 
      state: present

  - name: update listen address from 127.0.0.1 to 0.0.0.0
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: update protected-mode to no
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no

  - name: start service mongod, if not started
    ansible.builtin.service:
      name: redis
      state: started
      enabled: true