- name: payment component configuration
  hosts: payment
  become: true 
  tasks:
  - name: install python3 
    ansible.builtin.package:
      name: python3,gcc,python3-devel
      state: present

  - name: create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory

  - name: add the system user 'roboshop'
    ansible.builtin.user:
      name: roboshop
      system: true # makes the user a system account.
      home : /app
      shell: /sbin/nologin

  - name: download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip
    
  - name: extract application code /tmp/payment.zip
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app/
      remote_src: true

  - name: Install specified python requirements
    ansible.builtin.pip:
      requirements: /app/requirements.txt

  - name: copy service file to /etc/systemd/system/
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service
    
  - name: load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start service payment, if not started
    ansible.builtin.service:
      name: payment
      state: started
      enabled: true


  