  - name: application set-up
    include_role:
      name: common
      tasks_from: app-setup.yaml

  - name: install nodejs 
    include_role:
      name: common
      tasks_from: nodejs-setup.yaml

  - name: start cart service
    include_role:
      name: common
      tasks_from: systemd-service.yaml