- name: create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: add the system user 'roboshop'
  ansible.builtin.user:
    name: roboshop
    system: true # makes the user a system account.
    home : /app
    shell: /sbin/nologin