  - name: load the service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start service catalogue, if not started
    ansible.builtin.service:
      name: {{ component }}
      state: started
      enabled: true
